/// Generic application constants.
abstract class AppConstant {
  static const int otpTextLength = 6;
  static const int encryptionLength = 16;
  static const String android = 'android';
  static const String ios = 'ios';
  static const String web = 'web';
  static const double smallDeviceHeight = 800;
  static const double webPixelWidth = 1200;
  static const double mobilePixelWidth = 600;
  static const String en = 'en';
  static const String hi = 'hi';
  static const String es = 'es';
  static const String updateApp = 'force_update_maintainance_config';
  static const String sentryUserId = 'user.name';
  static const String sentryUserEmail = 'user.name@brainvire.com';
  static const String playStoreURL =
      'https://play.google.com/store/apps/details?id=';
  static const String appstoreURL = 'https://apps.apple.com/app/';
  static const String appId = '';
  static const String stage = 'stage';
  static const String prod = 'prod';
  static const String analyticsLoginSubmit = 'login_submit';
  static const String analyticsDashboardScreen = 'dashboard';
  static const String sentryAuthTagKey = 'auth';
  static const String sentryAuthTagAnonymous = 'anonymous';
  static const String sentryAuthLoginSuccess = 'login_success';
  static const String analyticsDashboardTabPrefix = 'dashboard_tab_';
  static const String analyticsStartQuizSuffix = '_start_quiz';
  static const String analyticsDifficultyPrefix = 'difficulty_';
  static const String analyticsSettingsLanguage = 'settings_language';
  static const String analyticsSettingsSound = 'settings_sound';
  static const String analyticsLeaderboardScreen = 'leaderboard';
  static const String analyticsAchievementsScreen = 'achievements';
  static const String quizLevelKey = 'quiz_level_key';
  static const String quizBestScoreKey = 'quiz_best_score_key';
  static const String quizPlayedCountKey = 'quiz_played_count_key';
  static const String isSoundEnabledKey = 'is_sound_enabled_key';
  static const int firstQuizUnlockCount = 1;
  static const int quizExplorerUnlockCount = 5;
  static const int scoreChampionUnlockThreshold = 70;
  static const int quizTotalQuestions = 10;
  static const int quizPointsPerCorrect = 10;
  static const int quizEasySeconds = 20;
  static const int quizMediumSeconds = 15;
  static const int quizHardSeconds = 10;
  static const String userDisplayName = 'Player';
}
