name: app_sentry
description: Sentry crash reporting and API tracing.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  network:
    path: ../network
  sentry_flutter: ^8.4.0
  sentry_logging: ^8.4.0

dev_dependencies:
  flutter_lints: ^2.0.3
