name: storage
description: Data storage - SharedPref, encrypted local storage.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  encrypt: ^5.0.1
  config:
    path: ../config
  get_storage: ^2.1.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.3
