export 'dart:convert';
export 'dart:isolate';
export 'dart:math';

export 'package:auto_route/auto_route.dart';
export 'package:device_info_plus/device_info_plus.dart';
export 'package:equatable/equatable.dart';
export 'package:firebase_analytics/firebase_analytics.dart';
export 'package:firebase_auth/firebase_auth.dart';
export 'package:firebase_core/firebase_core.dart';
export 'package:firebase_crashlytics/firebase_crashlytics.dart';
export 'package:firebase_messaging/firebase_messaging.dart';
export 'package:firebase_remote_config/firebase_remote_config.dart';
export 'package:flutter/foundation.dart';
export 'package:flutter/material.dart';
export 'package:flutter/services.dart';
export 'package:flutter_easyloading/flutter_easyloading.dart';
export 'package:flutter_web_plugins/url_strategy.dart';
export 'package:freezed_annotation/freezed_annotation.dart';
export 'package:intl/date_symbol_data_local.dart';
export 'package:logger/logger.dart';
export 'package:network_cache_interceptor/network_cache_interceptor.dart';
export 'package:path_provider/path_provider.dart';
export 'package:permission_handler/permission_handler.dart';
export 'package:shimmer/shimmer.dart';
export  'package:universal_html/html.dart' show window;
export 'package:url_launcher/url_launcher.dart';

export '../../app/app.dart';
export '../../base/base.dart';
export '../../gen/assets.gen.dart';
export '../../gen/fonts.gen.dart';
export '../../modules/modules.dart';
export '../../service/service.dart';
export 'utils.dart';
